#!/bin/sh

set -e
umask 0002

OPTIONS="--show suffix --relation-base /etc/device/services/ldap/suffix --relation-name name --relation-suffix .txt --relation suffix --required --integer-minimum 1 --integer-maximum 65534 --integer replica-id --select-base /usr/libexec/device/services/ldap/replication/roles.txt --select role"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@" | cat

fi

