#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --set index --index index --required --hostname name --distinguished-name suffix --relation-base /etc/device/services/ldap-server/instance --relation-name instance --relation-suffix .txt --relation instance "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart dirsrv-postdiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --set index --index index --required --hostname name --distinguished-name suffix --relation-base /etc/device/services/ldap-server/instance --relation-name instance --relation-suffix .txt --relation instance "$@" | cat

fi

