#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --add index --index index --hostname instance --port port --fqdn tls-dns --required --fqdn hostname "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart dirsrv-postdiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --add index --index index --hostname instance --port port --fqdn tls-dns --required --fqdn hostname "$@"

fi

