#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

if [ "$1" == "--" ]; then

  counter=2
  while [ $counter -lt $# ]; do
    if [ "${!counter}" = "hostname" ]; then
      ((counter++))
      redwax-tool --quiet \
	          --pem-in="/etc/pki/tls/private/*" \
                  --pem-in="/etc/pki/tls/certs/*" \
                  --filter=verify \
                  --filter-hostname="${!counter}" || { echo "Error: could not verify a certificate matching: ${!counter}"; exit 1; }
      break;
    fi
    ((counter+=2))
  done

  /usr/libexec/device-set --add index --index index --port port --fqdn tls-dns --required --fqdn hostname --relation-base /etc/device/services/ldap-server/instance --relation-name instance --relation-suffix .txt --relation instance "$@"

  find /etc/device/services/ldap-server/instance/ -mindepth 1 -maxdepth 1 -type l | \
  while read line; do

    if test -f "$line/disabled.bin"; then
      continue;
    fi

    if test ! -f "$line/instance.txt"; then
      continue;
    fi
    instance="$(head $line/instance.txt)"

    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart "dirsrv-postdiscovery@${instance}.service"

  done

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --add index --index index --port port --fqdn tls-dns --required --fqdn hostname --relation-base /etc/device/services/ldap-server/instance --relation-name instance --relation-suffix .txt --relation instance "$@" | cat

fi

