#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --mark index --index index "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart dirsrv-postdiscovery.service

  /usr/libexec/device-set --reindex index --index index

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --mark index --index index "$@"

fi

