#!/bin/sh

set -e
umask 0002

tmpdir="$(mktemp -d)"
trap 'rm -rf -- "${tmpdir}"' EXIT

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --add index --index index --required --integer-minimum 1 --integer-maximum 65534 --integer replica-id --select-base "/usr/libexec/device/services/ldap-server/replication/roles.txt" --select role --relation-base /etc/device/services/ldap-server/suffix --relation-name name --relation-suffix .txt --relation suffix "$@"

  find /etc/device/services/ldap-server/instance/ -mindepth 1 -maxdepth 1 -type l | \
  while read line; do

    if test -f "$line/disabled.bin"; then
      continue;
    fi

    if test ! -f "$line/name.txt"; then
      continue;
    fi
    instance="$(head $line/name.txt)"

    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart "dirsrv-postdiscovery@${instance}.service"

  done

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --add index --index index --required --integer-minimum 1 --integer-maximum 65534 --integer replica-id --select-base "/usr/libexec/device/services/ldap-server/replication/roles.txt" --select role --relation-base /etc/device/services/ldap-server/suffix --relation-name name --relation-suffix .txt --relation suffix "$@" | cat

fi

