#!/bin/sh

set -e
umask 0002

OPTIONS="--show name --hostname name --show-table name,tls-dns,suffix --required --fqdn tls-dns --relation-base /etc/device/services/ldap/suffix --relation-name name --relation-suffix .txt --relation suffix"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@" | cat

fi


