#!/bin/bash
  
#
# 389 Directory Server Postdiscovery
# ==================================
#
# This script autogenerates any required 389ds databases.

set -e

#
# Silence warnings with runuser.
cd /tmp


#
# Add/remove ldap instances

find /etc/device/services/ldap-server/suffix/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  target=$(readlink -f "$line")

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  bename="$(head $line/name.txt)"

  if test ! -f "$line/suffix.txt"; then
    continue;
  fi
  suffix="$(head $line/suffix.txt)"

  instance="$(head $line/instance.txt)"

  # add new instances
  if test -f "$line/added"; then

    instance="$(head $line/instance.txt)"

    if test ! -d "/etc/dirsrv/slapd-${instance}"; then
      logger -t dirsrv-postdiscovery "ignoring directory server backend ${bename} with suffix ${suffix}: instance ${instance} does not exist."
      continue
    fi

    # add instance
    logger -t dirsrv-postdiscovery "adding directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
    dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend create --suffix "${suffix}" --be-name "${bename}" || echo "Could not create suffix" > "$line/error"
    if test ! -f "$line/error"; then
      logger -t dirsrv-postdiscovery "added directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
    else
      logger -t dirsrv-postdiscovery "failed to add directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
    fi

    rm -f "$line/added"

  # update instances
  elif test -f "$line/updated"; then


    rm -f "$line/updated"

  # remove old instances
  elif test -f "$line/removed"; then

    instance="$(head $line/instance.txt)"

    # remove instance, but only if no error was created making the database
    if test ! -f "$line/error" -a -d "/etc/dirsrv/slapd-${instance}"; then
      logger -t dirsrv-postdiscovery "removing directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
      expect <<- EOF
set timeout -1
spawn dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend delete "${bename}"
match_max 100000
expect {
  "Type 'Yes I am sure' to continue: " {
    send -- "Yes I am sure"
    expect -exact "Yes I am sure"
    send -- "\r"
    expect eof
  }
  eof {
    exit 1
  }
}
EOF
      if [ $? -eq 0 ]; then
        logger -t dirsrv-postdiscovery "removed directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
      else
        logger -t dirsrv-postdiscovery "failed to remove directory server backend ${bename} with suffix ${suffix} to instance ${instance}, forgetting this suffix."
      fi
    fi

    # remove folder
    rm -f "${target}"/*
    rmdir "${target}"
    rm -f "${line}"
  fi

done

