#!/bin/bash
  
#
# 389 Directory Server Postdiscovery - suffix
# ===========================================
#
# This script adds/removes suffixes to/from instances.

set -e


#
# Add/update/remove ldap backends/suffixes

find /etc/device/services/ldap-server/suffix/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  target=$(readlink -f "$line")

  if test ! -f "$line/userroot.txt"; then
    continue;
  fi
  bename="$(head $line/userroot.txt)"

  if test ! -f "$line/suffix.txt"; then
    continue;
  fi
  suffix="$(head $line/suffix.txt)"

  if [ ! -e "$line/instance.d/name.txt" ]; then

    # remove any orphaned configs
    if test -f "$line/removed"; then

      rm -f "${target}"/*
      rmdir "${target}"
      rm -f "${line}"

    fi

    continue;
  fi
  instance="$(head $line/instance.d/name.txt)"

  if [ "${instance}" != "${1}" ]; then
    continue;
  fi

  # add new instances
  if test -f "$line/added"; then

    if test ! -d "/etc/dirsrv/slapd-${instance}"; then
      logger -t dirsrv-postdiscovery "ignoring directory server backend ${bename} with suffix ${suffix}: instance ${instance} does not exist."
      continue
    fi

    # add instance
    logger -t "dirsrv-postdiscovery@${instance}" "adding directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
    dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend create --suffix "${suffix}" --be-name "${bename}" --create-suffix || echo "Could not create suffix" > "$line/error"
    if test ! -f "$line/error"; then
      logger -t "dirsrv-postdiscovery@${instance}" "added directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
    else
      logger -t "dirsrv-postdiscovery@${instance}" "failed to add directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
    fi

    rm -f "$line/added"

  # update instances
  elif test -f "$line/updated"; then


    rm -f "$line/updated"

  # remove old instances
  elif test -f "$line/removed"; then

    # remove instance, but only if no error was created making the database
    if test ! -f "$line/error" -a -d "/etc/dirsrv/slapd-${instance}"; then
      logger -t "dirsrv-postdiscovery@${instance}" "removing directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
      expect <<- EOF || echo "Could not remove suffix" > "$line/error"
set timeout -1
spawn dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend delete "${bename}"
match_max 100000
expect {
  "Type 'Yes I am sure' to continue: " {
    send -- "Yes I am sure"
    expect -exact "Yes I am sure"
    send -- "\r"
    expect eof
  }
  eof {
    exit 1
  }
}
EOF
      if test ! -f "$line/error"; then
        logger -t "dirsrv-postdiscovery@${instance}" "removed directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
      else
        logger -t "dirsrv-postdiscovery@${instance}" "failed to remove directory server backend ${bename} with suffix ${suffix} to instance ${instance}, forgetting this suffix."
      fi
    fi

    # remove folder
    rm -f "${target}"/*
    rmdir "${target}"
    rm -f "${line}"
  fi

done


