#!/bin/bash

#
# 389 Directory Server Autodiscovery
# ==================================
#
# This script autogenerates any required 389ds instances.

set -e
umask 0007

exec 2> >(logger -t ${0})

request="${1}"
instance="${2}"

#
# Handle the cleanup
# ------------------
cleanup_before_exit () {
  if [ -d "${tmpdir}" ]; then
    rm -rf "${tmpdir}"
  fi
}
# be in a temporay workspace (this works on linux and macosx)
tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
# trap catches the exit signal and runs the specified function
trap cleanup_before_exit EXIT
# be in our directory
cd "${tmpdir}"


#
# Per instance? Run all scripts

if [ $# -gt 1 ]; then

  logger -t "dirsrv-autodiscovery@${instance}" "running autodiscovery for directory server instance ${instance}..."

  find "$0.d" -type f -executable | sort | \
  while read x; do
    "$x" "${request}" "${instance}" < /dev/null || touch error;
  done

  if test ! -f "error"; then
    logger -t "dirsrv-autodiscovery@${instance}" "completed autodiscovery for directory server instance ${instance}."
    exit 0
  else
    logger -t "dirsrv-autodiscovery@${instance}" "failed autodiscovery for directory server instance ${instance}."
    exit 1
  fi

fi

#
# Add/remove ldap instances

find /etc/device/services/ldap/instance/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  instance="$(head -n 1 $line/name.txt)"

  systemctl --no-block restart "dirsrv-autodiscovery@${instance}"

done

