#!/bin/bash

#
# 389 Directory Server Autodiscovery
# ==================================
#
# This script autogenerates any required 389ds instances.

set -e
umask 0007

exec 2> >(logger -t ${0})

request="${1}"
instance="${2}"


#
# Per instance? Run all scripts

if [ $# -gt 1 ]; then

  logger -t "dirsrv-autodiscovery@${instance}" "running autodiscovery for directory server instance ${instance}..."

  if /usr/bin/sequence -s daemon.info -b "/usr/libexec" "device-autodiscovery/389ds.d" "${request}" "${instance}" < /dev/null; then
    logger -t "dirsrv-autodiscovery@${instance}" "completed autodiscovery for directory server instance ${instance}."
    exit 0
  else
    logger -t "dirsrv-autodiscovery@${instance}" "failed autodiscovery for directory server instance ${instance}: $(cat error) ${request} ${instance}"
    exit 1
  fi

fi

#
# Add/remove ldap instances

find /etc/device/services/ldap/instance/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  instance="$(head -n 1 $line/name.txt)"

  systemctl --no-block restart "dirsrv-autodiscovery@${instance}"

done

