#!/bin/bash
  
#
# 389 Directory Server Postdiscovery
# ==================================
#
# This script autogenerates any required 389ds databases.

set -e

exec 2> >(logger -t ${0})


#
# Handle the cleanup
# ------------------
cleanup_before_exit () {
  if [ -d "${tmpdir}" ]; then
    rm -rf "${tmpdir}"
  fi
}
# be in a temporay workspace (this works on linux and macosx)
tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
# trap catches the exit signal and runs the specified function
trap cleanup_before_exit EXIT
# be in our directory
cd "${tmpdir}"



#
# Per instance? Run all scripts

if [ $# -ne 0 ]; then

  instance="${1}"

  logger -t "dirsrv-postdiscovery@${instance}" "running postdiscovery for directory server instance ${instance}..."

  find "$0.d" -type f -executable | sort | \
  while read x; do
    "$x" "${instance}" < /dev/null || touch error;
  done

  if test ! -f "error"; then
    logger -t "dirsrv-postdiscovery@${instance}" "completed postdiscovery for directory server instance ${instance}."
    exit 0
  else
    logger -t "dirsrv-postdiscovery@${instance}" "failed postdiscovery for directory server instance ${instance}."
    exit 1
  fi

fi

