#!/bin/sh

set -e
umask 0002

OPTIONS="--add name \
         --hostname name \
         --required --hostname userroot \
         --distinguished-name suffix \
         --relation-base /etc/device/services/ldap/instance --relation-name name --relation-suffix .txt --relation instance
         --lock /etc/device/services/ldap/"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart dirsrv-postdiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@" | cat

fi

