#!/bin/sh

#
# PKI Certificates Autodiscovery - 389ds replication certificate
# ==============================================================
#
# This script detects certificates for 389ds replication certificates.

set -e
umask 0027

if test ! -d /run/dirsrv/; then
  exit 0;
fi

request="${1}"
uuid="${2}"

#
# Configure certs/keys

if test "${request}" == "reload" -o "${request}" == "restart"; then

  find /etc/device/services/ldap/replication/incoming/ -mindepth 1 -maxdepth 1 -type l | \
  while read line; do

    if test ! -f "$line/suffix.d/instance.d/name.txt"; then
      continue;
    else
      instance="$(head -n 1 $line/suffix.d/instance.d/name.txt)"
    fi

    if test ! -L "$line/certificate.d"; then
      continue;
    else
      target=$(readlink -f "$line/certificate.d")
      uuid="$(basename $target)"
    fi

    systemctl --no-block try-restart "dirsrv-postdiscovery@${instance}"

  done

fi


