#!/bin/sh

set -e
umask 0002

OPTIONS="--set instance --port port --symlink-base /etc/pki/tls/certs --symlink-suffix .crt --symlink ca-certificate --required --relation-base /etc/device/services/ldap/instance --relation-name name --relation-suffix .txt --relation instance --relation-base /etc/device/system/pki/certificates --relation-name name --relation-suffix .txt --relation certificate"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart dirsrv-postdiscovery.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@" | cat

fi

