#!/bin/bash

#
# PKI Certificates Autodiscovery - 389ds tls
# ==========================================
#
# This script detects certificates for 389ds tls.

set -e
umask 0027

if test ! -d /run/dirsrv/; then
  exit 0;
fi

exec 2> >(logger -t ${0})

request="${1}"
uuid="${2}"

#
# Configure certs/keys

if test "${request}" == "reload" -o "${request}" == "restart"; then

  find /etc/device/services/ldap/tls/ -mindepth 1 -maxdepth 1 -type l | \
  while read line; do

    if test ! -f "$line/instance.d/name.txt"; then
      continue;
    else
      instance="$(head -n 1 $line/instance.d/name.txt)"
    fi

    if test ! -L "$line/certificate.d"; then
      continue;
    else
      target=$(readlink -f "$line/certificate.d")
      if test "${uuid}" != "$(basename $target)"; then
        continue;
      fi
    fi

    systemctl --no-block try-restart "dirsrv-autodiscovery@${instance}"

  done

fi


