#!/bin/sh

#
# 389 Directory Server Autodiscovery
# ==================================
#
# This script autogenerates any required 389ds instances.

set -e
umask 0007

request="${1}"

#
# Add/remove ldap instances

find /etc/device/services/ldap/instance/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  instance="$(head -n 1 $line/name.txt)"

  systemctl --no-block restart "dirsrv-autodiscovery@${instance}"

done

