#!/bin/sh
  
#
# 389 Directory Server Postdiscovery - suffix
# ===========================================
#
# This script adds/removes suffixes to/from instances.

set -e

request="${1}"
instance="${2}"

#
# Add/update/remove ldap backends/suffixes

find /etc/device/services/ldap/suffix/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  if [ ! -e "$line/instance.d/name.txt" ]; then
    continue;
  fi
  if [ "${instance}" != "$(head $line/instance.d/name.txt)" ]; then
    continue;
  fi

  target=$(readlink -f "$line")

  if test ! -f "$line/userroot.txt"; then
    continue;
  fi
  bename="$(head $line/userroot.txt)"

  if test ! -f "$line/suffix.txt"; then
    continue;
  fi
  suffix="$(head $line/suffix.txt)"

  # remove old instances
  if test -f "$line/removed"; then

    # remove instance, but only if no error was created making the database
    if test ! -f "$line/error" -a -d "/etc/dirsrv/slapd-${instance}"; then
      logger -t "dirsrv-postdiscovery@${instance}" "removing directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
      expect <<- EOF || echo "Could not remove suffix" > "$line/error"
set timeout -1
spawn dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend delete "${bename}"
match_max 100000
expect {
  "Type 'Yes I am sure' to continue: " {
    send -- "Yes I am sure"
    expect -exact "Yes I am sure"
    send -- "\r"
    expect eof
  }
  eof {
    exit 1
  }
}
EOF
      if test ! -f "$line/error"; then
        logger -t "dirsrv-postdiscovery@${instance}" "removed directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
      else
        logger -t "dirsrv-postdiscovery@${instance}" "failed to remove directory server backend ${bename} with suffix ${suffix} to instance ${instance}, forgetting this suffix."
      fi
    fi

    # remove folder
    rm -f "${target}"/*
    rmdir "${target}"
    rm -f "${line}"

  # add new instances
  elif test -f "$line/added"; then

    if test ! -d "/etc/dirsrv/slapd-${instance}"; then
      logger -t dirsrv-postdiscovery "ignoring directory server backend ${bename} with suffix ${suffix}: instance ${instance} does not exist."
      continue
    fi

    # add instance
    logger -t "dirsrv-postdiscovery@${instance}" "adding directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
    retry --times=3 --until=success dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend create --suffix "${suffix}" --be-name "${bename}" --create-suffix || echo "Could not create suffix" > "$line/error"
    if test ! -f "$line/error"; then
      logger -t "dirsrv-postdiscovery@${instance}" "added directory server backend ${bename} with suffix ${suffix} to instance ${instance}."

      rm -f "$line/added"

    else
      logger -t "dirsrv-postdiscovery@${instance}" "failed to add directory server backend ${bename} with suffix ${suffix} to instance ${instance}."

      # leave added in place, we will try again

    fi

  # update instances
  elif test -f "$line/updated"; then

    rm -f "$line/updated"

  fi

done


