#!/bin/sh
  
#
# 389 Directory Server Postdiscovery
# ==================================
#
# This script autogenerates any required 389ds databases.

set -e
umask 0007

request="${1}"


# All instances
find /etc/device/services/ldap/instance/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  if test ! -f "$line/name.txt"; then
    continue;
  fi
  instance="$(head $line/name.txt)"

  /usr/bin/systemctl --no-block restart "dirsrv-postdiscovery@${instance}.service"

done

