#!/bin/sh

set -e
umask 0002

OPTIONS="--show name \
         --hostname name \
         --show-flags disabled \
         --show-table name \
         --flag X --polar disabled \
         --lock /etc/device/services/ldap/"

if [ "$1" == "--" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-tool ${OPTIONS} "$@"

fi

